SELECT * FROM ACCESSHISTORY; DESC ACCESSHISTORY;

SELECT * FROM CARD; DESC CARD;
SELECT * FROM smallgatecontroller.`GROUP`; DESC smallgatecontroller.`group`;
#UPDATE smallgatecontroller.`group` SET GROUP_ID = 'GR002' WHERE GROUP_ID = 'G002'
SELECT * FROM CARDGROUP; DESC CARDGROUP;
#UPDATE CARDGROUP SET GROUP_ID = 'GR002' WHERE GROUP_ID = 'GR999'

SELECT * FROM GATE; DESC GATE;
SELECT * FROM AREA; DESC AREA;

SELECT * FROM GROUPAREA; DESC GROUPAREA;
#UPDATE GROUPAREA SET GROUP_ID = 'GR002' WHERE GROUP_ID = 'GR999'

#SELECT * FROM CARD FOR UPDATE
#COMMIT;

#VERSION 2.0 FOR ACCESSABLE
SELECT *
FROM CARDGROUP CG
JOIN GROUPAREA GA ON (CG.GROUP_ID = GA.GROUP_ID)
JOIN GATE G ON (GA.AREA_ID = G.AREA_ID AND G.GATE_ID = 'GT002')
WHERE CG.CARD_ID = 'SOME_CARD_ID'
LIMIT 1

#VERSION 1.0 FOR ACCESSABLE
SELECT *
FROM CARDGROUP
WHERE GROUP_ID
	(	SELECT GROUP_ID
		FROM GROUPAREA
		WHERE AREA_ID = 
			(	SELECT AREA_ID
				FROM GATE
				WHERE GATE.GATE_ID = 'SOME_GATE_ID'
			)
	)	AND
	CARD_ID = 'SOME_CARD_ID'
				